#ifndef __STAT_STAGE_H
#define __STAT_STAGE_H

enum StatStage
{
    STATSTAGE_NULL = 0x0,
    STATSTAGE_ATTACK = 0x1,
    STATSTAGE_DEFENSE = 0x2,
    STATSTAGE_SPECIAL_ATTACK = 0x3,
    STATSTAGE_SPECIAL_DEFENSE = 0x4,
    STATSTAGE_SPEED = 0x5,
    STATSTAGE_ACCURACY = 0x6,
    STATSTAGE_EVASION = 0x7,
};

#endif // __STAT_STAGE_H
