@ECHO OFF 

SET GCC=arm-none-eabi-g++
SET LD=arm-none-eabi-ld
SET JAVA=java
SET CTRMAP_DIR=PasteHereYourCTRMapPath
SET OUTPUT_DIR=PasteHereYourOutputPath

SET CTRMAP=%CTRMAP_DIR%\CTRMAP.jar
SET RPMTOOL=%JAVA% -cp %CTRMAP% rpm.cli.RPMTool

SET BUILD_DIR=build
SET PATCHES_DIR=Patches
SET SWAN_DIR=ExternalDependencies\swan
SET NK_DIR=ExternalDependencies\NitroKernel\include

SET GAME_VARS_PATCH=GameVariables
SET BATTL_UPG_PATCH=BattleUpgrade
SET KOL_ITEMS_PATCH=KOLItems

SET GAME_VARS_SRC=%PATCHES_DIR%\%GAME_VARS_PATCH%.cpp
SET BATTL_UPG_SRC=%PATCHES_DIR%\%BATTL_UPG_PATCH%.cpp
SET KOL_ITEMS_SRC=%PATCHES_DIR%\%KOL_ITEMS_PATCH%.cpp
SET KOL_ITEMS_ARM_SRC=%PATCHES_DIR%\%KOL_ITEMS_PATCH%.S

SET GAME_VARS_ELF=%BUILD_DIR%\%GAME_VARS_PATCH%.o
SET BATTL_UPG_ELF=%BUILD_DIR%\%BATTL_UPG_PATCH%.o
SET KOL_ITEMS_ELF=%BUILD_DIR%\%KOL_ITEMS_PATCH%.o
SET KOL_ITEMS_ARM_ELF=%BUILD_DIR%\%KOL_ITEMS_PATCH%ARM.o

SET OUTPUT_PATCH=White2Updates
SET OUTPUT_ELF=%BUILD_DIR%\%OUTPUT_PATCH%.elf
SET OUTPUT_DLL=%OUTPUT_DIR%\%OUTPUT_PATCH%.dll

SET ESDB=ESDB.yml

SET COMPILATION_INCLUDES=-I %SWAN_DIR% -I %NK_DIR%
SET COMPILATION_FLAGS=-r -mthumb -march=armv5t -Os
SET LINKING_FLAGS=--fourcc DLXF --generate-relocations

mkdir %BUILD_DIR% >nul 2>&1

ECHO Compiling patches...
%GCC% %GAME_VARS_SRC% %COMPILATION_INCLUDES% -o %GAME_VARS_ELF% %COMPILATION_FLAGS%
%GCC% %BATTL_UPG_SRC% %COMPILATION_INCLUDES% -o %BATTL_UPG_ELF% %COMPILATION_FLAGS%
%GCC% %KOL_ITEMS_SRC% %COMPILATION_INCLUDES% -o %KOL_ITEMS_ELF% %COMPILATION_FLAGS%
%GCC% %KOL_ITEMS_ARM_SRC% -o %KOL_ITEMS_ARM_ELF% %COMPILATION_FLAGS%
ECHO ---

ECHO Merging compilation...
%LD% -r -o %OUTPUT_ELF% %GAME_VARS_ELF% %BATTL_UPG_ELF% %KOL_ITEMS_ELF% %KOL_ITEMS_ARM_ELF%
ECHO --- 

ECHO Linking patch...
%RPMTOOL% -i %OUTPUT_ELF% -o %OUTPUT_DLL% --esdb %ESDB% %LINKING_FLAGS%
ECHO ---

PAUSE