#ifndef __FEATURE_SETTINGS_H
#define __FEATURE_SETTINGS_H	

#define ADD_LEVEL_CAP true
#define DISABLE_EVS true
#define RARE_CANDY_IGNORE_LVL_CAP false

#define ADD_INFINITE_RARE_CANDY false
#define INFINITE_CANDY_ID IT0622
#define REGIT_INFINITE_CANDY REGIT_UNUSED_34

#define ADD_INFINITE_REPEL false
#define REPEL_SHAKING_GRASS false
#define INFINITE_REPEL_ID IT0079_REPEL
#define REGIT_INFINITE_REPEL REGIT_UNUSED_35
#define ACTID_REPEL 254

#define DYNAMIC_SPEED true
#define DYNAMIC_SPEED_DEBUG false

#define GEN6_CRIT true

#define WEATHER_ABILITY_TURNS 255 // 255 means infinite turns

#define EXPAND_ABILITIES false
#define GEN9_PROTEAN false
#define GEN7_SYMBIOSIS_GEMS false
#define GEN6_PARENTAL_BOND false
#define EMERGENCY_EXIT_DEBUG true
#define BERSERK_DEBUG true
#define GEN9_BATTLE_BOND false

#define EXPAND_MOVES false

#define EXPAND_FIELD_EFFECTS (EXPAND_ABILITIES || EXPAND_MOVES)
#define TERRAIN_ABILITY_TURNS 255 // 255 means infinite turns
#define TERRAIN_GEN7_DMG false
#define ELECTRIC_TERRAIN_MOVE_ANIM MOVE351_SHOCK_WAVE
#define GRASSY_TERRAIN_MOVE_ANIM MOVE312_AROMATHERAPY
#define MISTY_TERRAIN_MOVE_ANIM MOVE054_MIST
#define PSYCHIC_TERRAIN_MOVE_ANIM MOVE505_HEAL_PULSE

// VARIABLES
#define LVL_CAP_VAR 16415

// MESSAGE IDs
// Game Text - File 6
#define BAG_ITEMUSED_MSGID 63
#define BAG_REPELEND_MSGID 64
// Game Text - File 19
#define BATTLE_ASSAULTVEST_MSGID 201
#define BATTLE_ELECTRIC_TERRAIN_MSGID 202
#define BATTLE_GRASSY_TERRAIN_MSGID 203
#define BATTLE_MISTY_TERRAIN_MSGID 204
#define BATTLE_PSYCHIC_TERRAIN_MSGID 205
#define BATTLE_TERRAIN_END_MSGID 206
#define BATTLE_PRIMORDIAL_SEA_MSGID 207
#define BATTLE_PRIMORDIAL_SEA_END_MSGID 208
#define BATTLE_PRIMORDIAL_SEA_IMMUNE_MSGID 209
#define BATTLE_DESOLATE_LAND_MSGID 210
#define BATTLE_DESOLATE_LAND_END_MSGID 211
#define BATTLE_DESOLATE_LAND_IMMUNE_MSGID 212
#define BATTLE_DELTA_STREAM_MSGID 213
#define BATTLE_DELTA_STREAM_END_MSGID 214
#define BATTLE_DELTA_STREAM_RESISTANCE_MSGID 215
#define BATTLE_BLADE_FORME_MSGID 216
#define BATTLE_SHIELD_FORME_MSGID 217
#define BATTLE_SHIELDS_DOWN_INACTIVE_MSGID 218
#define BATTLE_SHIELDS_DOWN_ACTIVE_MSGID 219
// Game Text - File 18
#define BATTLE_CLEARAMULET_MSGID 878
#define BATTLE_ELECTRIC_TERRAIN_STATUS_MSGID 1159
#define BATTLE_MISTY_TERRAIN_STATUS_MSGID 1162
#define BATTLE_AROMA_VEIL_MSGID 1165
#define BATTLE_FLOWER_VEIL_MSGID 1168
#define BATTLE_SWEET_VEIL_MSGID 1171
#define BATTLE_SYMBIOSIS_MSGID 1174
#define BATTLE_DARK_AURA_MSGID 1177
#define BATTLE_FAIRY_AURA_MSGID 1180
#define BATTLE_AURA_BREAK_MSGID 1183
#define BATTLE_SCHOOLING_ACTIVE_MSGID 1186
#define BATTLE_SCHOOLING_INACTIVE_MSGID 1189
#define BATTLE_DISGUISE_MSGID 1192
#define BATTLE_BATTLE_BOND_MSGID 1195
#define BATTLE_POWER_CONSTRUCT_MSGID 1198
// Game Text - File 178
#define POKELIST_NATURECHANGE_MSGID 73
#define POKELIST_ABILITYCHANGE_MSGID 74
#define POKELIST_IVMODALL_MSGID 75
#define POKELIST_IVMODSINGLE_MSGID 76

#endif
